filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /etc/keepalived/monitor_dig.log

#output.console:
#  pretty: true

setup.template.enabled: true
setup.dashboards.enabled: false

output.elasticsearch:
  hosts: ["10.24.1.252:9200"]
#  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
#  setup.template.name: "customname"
#  setup.template.pattern: "customname-*"
#  setup.dashboards.index: "customname-*"
  username: "elastic"
  password: "123456"
